new commit with black hole and loop hole
CIS580/space-raiders pull request #15
Opened 2018-12-08 20:53 UTC by zhechao

black-hole.png added
loop-hole.js added
blackhole.js added

2018-12-08 23:32 UTC, zhechao commented
* all mentioned loop hole problems solved
* re-checked black hole, not sure whether the force is too big, if it does, please let me know

2018-12-09 14:46 UTC, ksu-shanemat requested changes
I have checked your code and I am glad to say, that it seems to work. However, I have a few more objections.

First, your indentation is completely inconsistent. Would you please unify it? An ideal would be 4 spaces per indentation since this is what the rest of the team uses.

Second, as Jozef mentioned, a lot of your code can be simplified using utility classes, would you please consider using them?

Third, when testing your loophole I thought it might be pretty useful to be able to specify even the position of the exit end of the loophole. This would provide way more flexibility for generating levels instead of relying on the random generator. I think you can still leave the random option there, too.

The last idea is about the loophole visual representation. I had a hard time when playing for two main reasons. One was that I was not able to distinguish the start and end position. Do you use different images or how do you indicate which is which? Also, would you mind making that image more fading instead of flashing? I would gradually change the alpha channel to achieve this behavior.

2018-12-09 21:04 UTC, zhechao commented
the four problems you mentioned (actually 3) are solved

2018-12-10 05:26 UTC, RealJohnSmith requested changes
I left a lot comments in code, please fix it or defend your decisions why you made things the way you  did. It could also help if you squashed everything so it is one single commit. Or two, one doing only the black hole functionality, other one doing only the portal (loop hole) functionality
Thanks

2018-12-10 05:26 UTC, RealJohnSmith commented on src/space/objects/pattern/collisionHandler.js
> -            case Type.BLACK_HOLE | Type.ASTEROID:
Why is Asteroid not affected by Black Hole?

2018-12-10 05:26 UTC, RealJohnSmith commented on src/space/objects/pattern/collisionHandler.js
>              case Type.BLACK_HOLE | Type.EXPLOSIVE:
But explosive barrels and such are?

2018-12-10 05:26 UTC, RealJohnSmith commented on src/space/objects/realization/blackhole.js
> +    static generateBH(encounter){
What is this supposed to do? Where should it be called from? black hole is generated by encounter world generator, not by itself. And that is what constructor is for.

If it is supposed to be some sort of helper method, then name it accordingly, for example 'generateAtRandomPosition()'

2018-12-10 05:26 UTC, RealJohnSmith commented on src/space/objects/realization/blackhole.js
> +        super(encounter, Type.BLACK_HOLE,BH_RANGE, position);
Should be object radius BH_RADIUS, not BH_RANGE

2018-12-10 05:26 UTC, RealJohnSmith commented on src/space/objects/realization/blackhole.js
> +    update(deltaT, input){
Update function does not take any parameter `input`. Thats even in the documentation you wrote there. WTF?

2018-12-10 05:26 UTC, RealJohnSmith commented on src/space/objects/realization/blackhole.js
> +    update(deltaT, input){
And you dont even use it in your code. What values do you expect it will have?

2018-12-10 05:26 UTC, RealJohnSmith commented on src/space/objects/realization/blackhole.js
> +        if(this.wrapInterval <= 0){
What the hell does this thing?
Can you rewrite it in such a way that will make it readable?
Some tips:
Dont use px amounts directly anywhere in conditions or variables. Use tile position indices and when rendering, multiply by the tile width (which should be calculated runtime from amount of tiles in each direction and size of texture so the entire chopping thing is invariant to texture size -> texture can be replaced with one with half or double resolution and everything will still work)

`update` function has no business doing anything at all with render logic. Wrap this texture chopping to some other function (not update) and call that from render, not update

2018-12-10 05:26 UTC, RealJohnSmith commented on src/space/objects/realization/blackhole.js
> +        context.drawImage(this.bhImage,this.sourceX,this.sourceY,100,100,this.position.x - 50, this.position.y - 50, 100, 100);
What?
Why do you like so much the hardcoded values of everything. You even have existing constant `BH_RADIUS`
Is it so hard to use it for the thing it is supposed to be used?

2018-12-10 05:26 UTC, RealJohnSmith commented on src/space/objects/realization/blackhole.js
> +    gravitation(object){
name things properly, to reflect what they do. In this case it would be much better choice to name it `applyGravityTo` or something like that. If you just see text `gravitation` somewhere, there is no way you can understand what the hell it means. Is it the movie? Is it like "check if earth still has gravity and write result to logs" functionality? Or what!?

2018-12-10 05:26 UTC, RealJohnSmith commented on src/space/objects/realization/loop-hole.js
> +        this.inSourceX = 0;
naming, yet again. `isSourceX` sounds like x coordinate of input portal, nothing to do with assets/textures. 

Not to mention that you are setting in to hardcoded value. In costructor. Of every instance. Ever heard of constants? Oh wait, you did, you just create them and forget about them and use hardcoded numbers anyway, ignoring those constants

2018-12-10 05:26 UTC, RealJohnSmith commented on src/space/objects/realization/loop-hole.js
> +    static generateLH(encounter){
What is this supposed to do? Where should it be called from? black hole is generated by encounter world generator, not by itself. And that is what constructor is for.

If it is supposed to be some sort of helper method, then name it accordingly, for example 'generateAtRandomPosition()'

2018-12-10 05:26 UTC, RealJohnSmith commented on src/space/objects/realization/loop-hole.js
> +      	} while (this.outX == position.x && this.outY == position.y)
This condition will never be true, because you are comparing 2 floating point numbers which are not guaranteed to have full integer value.
You should check for radius around the this.poistion and this.out; You already have radius in `LH_RADIUS`, you can just double it (one of entry, one for exit) and check distance.
You might want to define minimal distance though, to not get teleported just 20px to the side.

2018-12-10 05:26 UTC, RealJohnSmith commented on src/space/objects/realization/loop-hole.js
> +        context.drawImage(this.lhImage,this.outSourceX,this.outSourceY,40,40,this.outPos.x - 20, this.outPos.y - 20, 40, 40);
`LH_RADIUS`, yet and yet...

2018-12-10 05:26 UTC, RealJohnSmith commented on src/space/objects/realization/loop-hole.js
> +        this.fadeInterval -= deltaT;
This entire thing is render related -> should be called from render, not update

2018-12-10 05:26 UTC, RealJohnSmith commented on src/space/objects/realization/loop-hole.js
> +    update(deltaT, input){
Update function does not take any parameter input. Thats even in the documentation you wrote there. WTF?

And you dont even use it in your code. What values do you expect it will have?

2018-12-10 05:26 UTC, RealJohnSmith commented on src/space/objects/realization/loop-hole.js
> +            if(this.fadeStatus){
`fadeStatus`? Do you mean `fadeDirection`? Nope, that doesn't really help when we have true/false values. What about `isFadingOut`? You see, a lot better name for a variable. Now it actually tells us what it holds

2018-12-10 05:26 UTC, RealJohnSmith commented on src/space/objects/pattern/collisionHandler.js
>          // TODO: Implement actual handling
Any reason why to leave the TODO comment? Are you planning on returning back and changing something?

2018-12-10 07:26 UTC, zhechao commented on src/space/objects/pattern/collisionHandler.js
> -            case Type.BLACK_HOLE | Type.ASTEROID:
If I change it back, the velocity of asteroids should be larger than 1.05 per millisecond. Otherwise, some asteroids will stay in the center of black hole.
Currently, I have changed it back, but let know if it wont work.

2018-12-10 07:27 UTC, zhechao commented on src/space/objects/pattern/collisionHandler.js
>              case Type.BLACK_HOLE | Type.EXPLOSIVE:
since I think barrels will not be in map for long period, asteroids will.

2018-12-10 07:28 UTC, zhechao commented on src/space/objects/realization/blackhole.js
> +    static generateBH(encounter){
Okay, I will change it, and commit it when all problems are solved.

2018-12-10 07:32 UTC, zhechao commented on src/space/objects/realization/blackhole.js
> +        super(encounter, Type.BLACK_HOLE,BH_RANGE, position);
No, it was BH_RADIUS, but Iater I find if I do so, the gravitation will be only happened when object collide with black hole. And I assume the black hole will pull the objects but not destory the objects, so I think it is not necessary to creae antother BLACK_HOLE_RADIUS.

2018-12-10 07:36 UTC, zhechao commented on src/space/objects/realization/blackhole.js
> +        if(this.wrapInterval <= 0){
make black hole sprite work

2018-12-10 07:37 UTC, zhechao commented on src/space/objects/realization/blackhole.js
> +        context.drawImage(this.bhImage,this.sourceX,this.sourceY,100,100,this.position.x - 50, this.position.y - 50, 100, 100);
Okay, I will change it with BH_RADIUS

2018-12-10 07:37 UTC, zhechao commented on src/space/objects/realization/blackhole.js
> +    gravitation(object){
changed

2018-12-10 07:49 UTC, zhechao commented on src/space/objects/realization/loop-hole.js
> +      	} while (this.outX == position.x && this.outY == position.y)
if mapwidth and mapheight, they should return integers, but I will check minimal distance

2018-12-10 08:00 UTC, zhechao commented on src/space/objects/realization/loop-hole.js
> +            if(this.fadeStatus){
changed

2018-12-10 08:00 UTC, zhechao commented on src/space/objects/pattern/collisionHandler.js
>          // TODO: Implement actual handling
deleted

2018-12-10 08:09 UTC, zhechao commented on src/space/objects/realization/blackhole.js
> +    update(deltaT, input){
update() deleted all codes moved to render()

2018-12-10 08:13 UTC, zhechao commented on src/space/objects/realization/loop-hole.js
> +        context.drawImage(this.lhImage,this.outSourceX,this.outSourceY,40,40,this.outPos.x - 20, this.outPos.y - 20, 40, 40);
changed

2018-12-10 08:13 UTC, zhechao commented on src/space/objects/realization/loop-hole.js
> +        this.fadeInterval -= deltaT;
update() deleted all codes moved to render()

2018-12-10 08:13 UTC, zhechao commented on src/space/objects/realization/loop-hole.js
> +    update(deltaT, input){
update() deleted all codes moved to render()

2018-12-10 10:27 UTC, zhechao commented
commits suqashed

2018-12-10 14:47 UTC, ksu-shanemat commented
> commits squashed

No, they are not ... the PR still has 9 of them, whereas John requested (reasonably) one or two ;))

![image](https://user-images.githubusercontent.com/42660075/49739711-2ac9f400-fc58-11e8-90f0-7f4091010c4c.png)

2018-12-10 19:10 UTC, closed without merging